# Loads default set of integrations. Do not remove.
default_config:
  #bluetooth:
######################################
# Home Assistant setup
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.0/24
    - 100.64.0.0/10 # <- WireGuard network

homeassistant:
  internal_url: http://192.168.1.159:8123
  external_url: https://hacs.kaffeogkage.cc

  #customize: !include customize.yaml
  packages: !include_dir_merge_named configurations/packages/
  #allowlist_external_dirs:
  #- /config/www/rest
  #- /config

######################################
# Frontend setup
frontend:
  themes: !include_dir_merge_named themes

######################################
# Default includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

######################################
# Integrations without configuration
wake_on_lan:

######################################

# Configurations
binary_sensor: !include_dir_merge_list configurations/binary_sensor
#conversation: !include configurations/conversation.yaml
#fuelprices_dk: !include configurations/fuelprices.yaml
#group: !include_dir_merge_named configurations/groups
#intent_script: !include_dir_merge_named configurations/intent_script
#media_player: !include_dir_merge_list configurations/media_player
#powercalc: !include configurations/powercalc.yaml
#pyscript: !include configurations/pyscript.yaml
python_script:
#recorder: !include configurations/recorder.yaml
#rest: !include_dir_merge_list configurations/rest
#rest_command: !include configurations/rest_command.yaml
sensor: !include_dir_merge_list configurations/sensor
template: !include_dir_merge_list configurations/template
#shell_command: !include configurations/shell_commands.yaml
#switch: !include_dir_merge_list configurations/switch

#tts: !include configurations/tts.yaml
#zha: !include configurations/zha.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: DK

input_text:
  huskeliste_herman:
    name: Huskeliste Herman
    max: 255
  huskeliste_kamma:
    name: Huskeliste Kamma
    max: 255
  huskeliste_herman_next:
    name: Huskeliste Herman
    max: 255
  huskeliste_kamma_next:
    name: Huskeliste Kamma
    max: 255
  beskedliste_alle:
    name: beskederaula
    max: 255

input_boolean:
  smart_wash:
    name: Smart Wash
    initial: off # Default state is off when Home Assistant starts
    icon: mdi:dishwasher
  smart_wash_vaskemaskine:
    name: Smart Wash2
    initial: off # Default state is off when Home Assistant starts
    icon: mdi:washing-machine
  wash_today:
    name: Wash Today
    initial: off # Default state is off when Home Assistant starts
    icon: mdi:dishwasher
  wash_today_vaskemaskine:
    name: Wash Today Vaskemaskine
    initial: off
    icon: mdi:washing-machine

input_number:
  climate_temperature:
    name: Climate Temperature
    min: 15.5
    max: 30
    step: 0.5
    mode: slider
    initial: 22.5

input_select:
  washer_temperature:
    name: Washer Temperature
    options:
      - "30"
      - "40"
      - "60"
    initial: "40" # Default selected value
    icon: mdi:thermometer
  theme_selector:
    name: Theme Selector
    options:
      - Fluent Blue
      - Fluent Green
      - Fluent Orange
      - Fluent Purple
      - Fluent Red
      - Fluent Slate
      - Metro Blue
      - Metro Green
      - Metro Orange
      - Metro Purple
      - Metro Red
      - Metro Slate
    initial: Fluent Blue

#───────────────────────────────────────────────────────────────────────────────
# Pollen prognose og seneste pollental
#───────────────────────────────────────────────────────────────────────────────
pollen_dk:
  regions: # Possible values: øst, vest
    - vest
  pollen_types: # Possible values: alternaria, birk, bynke, cladosporium, el, elm, græs, hassel
    - alternaria
    - birk
    - bynke
    - cladosporium
    - el
    - elm
    - græs
    - hassel
#───────────────────────────────────────────────────────────────────────────────
# Eloverblik
#───────────────────────────────────────────────────────────────────────────────
camera:
  - platform: xiaomi_cloud_map_extractor
    name: l50_ultra_map_color
    host: !secret dreame_host
    token: !secret dreame_token
    draw: ["all", "segments"] # draws rooms
    # optional: customize colors per room in `colors:` section
