blueprint:
  name: Huskeliste fra ugeplan (LLM) – v4 (tekst, ingen JSON)
  description: >
    Udtrækker vigtige "husk"-punkter fra sensorens 'ugeplan'-attribut via LLM
    og udsender en færdig punktopstilling som ren tekst. Skriver en kort
    (trimmet) opsummering til input_text. Den fulde tekst lægges i
    event-data og kan gemmes i en template-sensor-attribut (ingen 255-char limit).
  domain: automation
  input:
    ugeplan_sensor:
      name: Ugeplan sensor
      selector:
        entity:
          filter:
            - domain: sensor
    output_helper:
      name: Output helper (input_text)
      selector:
        entity:
          filter:
            - domain: input_text
    conversation_agent:
      name: Conversation Agent
      default: conversation.chatgpt
      selector:
        text: {}
    event_name:
      name: Event-navn (valgfrit)
      description: Fx kamma_huskeliste_updated / herman_huskeliste_updated
      default: ""
      selector:
        text: {}

mode: single

triggers:
  - trigger: state
    entity_id: !input ugeplan_sensor
    attribute: ugeplan

conditions: []

actions:
  - variables:
      ugeplan_entity: !input ugeplan_sensor
      agent_id: !input conversation_agent
      out_entity: !input output_helper
      evt_name: !input event_name
      summary_response: ""

  - action: conversation.process
    data:
      agent_id: "{{ agent_id }}"
      text: >
        Givet ugeplanen nedenfor: Udtræk én linje pr. skoledag i den pågældende uge (mandag–fredag). Inkludér ALLE dage, også selvom det ikke nødvendigvis hører under det med særlig fokus. Så bare lav et kort notat om det.
            
        Formål:
        Som forælder vil jeg se, hvad der skal huskes pr. dag med SÆRLIG fokus på lektier (afleveringer/opgaver,læse), bøger/bibliotek, idræt/svømning og ture.

        Detektion (eksempler, ikke udtømmende):
        - Lektier: "lektier", "lektie", "aflevering", "opgave/opg.", "læselektier", "læs s.", "skriv", "stav", "øve".
        - Fag: "dansk", "matematik", "engelsk", "natur/teknologi", "historie", "tysk" m.fl. (angiv faget i parentes ved lektier, hvis muligt).
        - Bøger/bibliotek: "bog", "bøger", "læsebog", "bibliotek", "aflever bog".
        - Idræt/svømning: "idræt"/"idraet", "gymnastik", "bevægelse", "svømning", "svømmehal", "badetøj", "håndklæde", "svømmebriller".
        - Tur/udflugt: "tur", "udflugt", "ekskursion", "museum", "ude-dag", "skovtur".
        - Test: "nationale test", "nationale", "test"
        - Andet udstyr: "iPad/computer opladet", "høretelefoner", "penalhus", "madpakke særligt", "cykel", "hjelm", "byttepenge", "underskrift".

        Regler:
        1) Opret ét objekt per skoledag (man–fre) i ugen, sorteret stigende efter dato (YYYY-MM-DD). Brug datoer fra ugeplanen.
        2) Sæt lektier først i "message" med formatet: "Lektier (fag): kort beskrivelse". Hvis flere fag, adskil med "; ".
        3) Saml øvrige ting i samme "message", adskilt med "; " (fx "Idræt: idrætstøj og indendørssko; Svømning: badetøj og håndklæde; Bibliotek: aflever/medbring bøger; Tur: turtaske, drikkedunk").
        4) Maks 5000 tegn i "message". Vær ultrakonkis; fjern fyldord og gentagelser.
        5) Ingen linjeskift i "message". Brug dansk. Ingen dato-hallucinationer.
        6) Hvis ugeplanen angiver lektier "til torsdag", placér dem på den nævnte forfaldsdag (torsdag), ikke på annonceringsdagen.

        Det skal være i dette format:
        - **YYYY-MM-DD**: Beskeden ud fra de regler som er opstillet og detektion
        Ingen overskrift, ingen kodefence, ingen forklaring. Ingen linjeskift i hver linje.
        Vær ultra-konkis; fjern fyldord/gentagelser. Brug datoer fra ugeplanen.

        Ugeplan:
        {{ state_attr(ugeplan_entity, 'ugeplan') }}

    response_variable: summary_response

  - variables:
      huskeliste_text: >-
        {{ summary_response.response.speech.plain.speech
           | string
           | regex_replace(find='^\\s*```(?:json|yaml)?\\s*', replace='')
           | regex_replace(find='\\s*```\\s*$', replace='')
           | trim }}

  # Fyr event med den FÆRDIGE tekst (KORREKT syntaks)
  - choose:
      - conditions: "{{ (evt_name | default('') | trim) != '' }}"
        sequence:
          - event: !input event_name
            event_data:
              huskeliste_text: "{{ huskeliste_text }}"

  # Skriv en kort (trimmet) udgave til input_text (255-char limit)
  - action: input_text.set_value
    data:
      entity_id: !input output_helper
      value: "{{ huskeliste_text[:250] }}"
