blueprint:
  name: Huskeliste fra ugeplan (LLM) – v3
  description: >
    Trækker "husk"-punkter ud fra sensorens 'ugeplan'-attribut via LLM og skriver
    en kort opsummering til et input_text helper-felt. Robust JSON-parsing og
    beskæring til input_text længde.
  domain: automation
  input:
    ugeplan_sensor:
      name: Ugeplan sensor
      description: Sensoren med attributten 'ugeplan' (fx sensor.finderuphoj_skole_kamma)
      selector:
        entity:
          filter:
            - domain: sensor
    output_helper:
      name: Output helper (input_text)
      description: Hvor den menneskelige opsummering skal skrives
      selector:
        entity:
          filter:
            - domain: input_text
    conversation_agent:
      name: Conversation Agent
      description: Agent der bruges af conversation.process (fx conversation.chatgpt)
      default: conversation.chatgpt
      selector:
        text: {}
    event_name:
      name: Event-navn (valgfrit)
      description: Hvis angivet, affyres et event med dette navn efter parsing
      default: ""
      selector:
        text: {}

mode: single

# NEW-style trigger syntax
triggers:
  - trigger: state
    entity_id: !input ugeplan_sensor
    attribute: ugeplan

# (optional) conditions block can be empty
conditions: []

# NEW-style actions syntax
actions:
  - variables:
      ugeplan_entity: !input ugeplan_sensor
      agent_id: !input conversation_agent
      out_entity: !input output_helper
      evt_name: !input event_name
      summary_response: ""

  - action: conversation.process
    data:
      agent_id: "{{ agent_id }}"
      text: >
        Givet ugeplanen nedenfor: Udtræk én post pr. skoledag i den pågældende uge (mandag–fredag). Inkludér ALLE dage, også selvom det ikke nødvendigvis hører under det med særlig fokus. Så bare lav et kort notat om det.
            
        Formål:
        Som forælder vil jeg se, hvad der skal huskes pr. dag med SÆRLIG fokus på lektier (afleveringer/opgaver,læse), bøger/bibliotek, idræt/svømning og ture.

        Detektion (eksempler, ikke udtømmende):
        - Lektier: "lektier", "lektie", "aflevering", "opgave/opg.", "læselektier", "læs s.", "skriv", "stav", "øve".
        - Fag: "dansk", "matematik", "engelsk", "natur/teknologi", "historie", "tysk" m.fl. (angiv faget i parentes ved lektier, hvis muligt).
        - Bøger/bibliotek: "bog", "bøger", "læsebog", "bibliotek", "aflever bog".
        - Idræt/svømning: "idræt"/"idraet", "gymnastik", "bevægelse", "svømning", "svømmehal", "badetøj", "håndklæde", "svømmebriller".
        - Tur/udflugt: "tur", "udflugt", "ekskursion", "museum", "ude-dag", "skovtur".
        - Test: "nationale test", "nationale", "test"
        - Andet udstyr: "iPad/computer opladet", "høretelefoner", "penalhus", "madpakke særligt", "cykel", "hjelm", "byttepenge", "underskrift".

        Regler:
        1) Opret ét objekt per skoledag (man–fre) i ugen, sorteret stigende efter dato (YYYY-MM-DD). Brug datoer fra ugeplanen.
        2) Sæt lektier først i "message" med formatet: "Lektier (fag): kort beskrivelse". Hvis flere fag, adskil med "; ".
        3) Saml øvrige ting i samme "message", adskilt med "; " (fx "Idræt: idrætstøj og indendørssko; Svømning: badetøj og håndklæde; Bibliotek: aflever/medbring bøger; Tur: turtaske, drikkedunk").
        4) Maks 5000 tegn i "message". Vær ultrakonkis; fjern fyldord og gentagelser.
        5) Ingen linjeskift i "message". Brug dansk. Ingen dato-hallucinationer.
        6) Hvis ugeplanen angiver lektier "til torsdag", placér dem på den nævnte forfaldsdag (torsdag), ikke på annonceringsdagen.

        Outputformat (KUN gyldig JSON – ingen forklaring, ingen kodefence):
        [
          { "date": "YYYY-MM-DD", "message": "..." },
          { "date": "YYYY-MM-DD", "message": "..." }
        ]

        Ugeplan:
        {{ state_attr(ugeplan_entity, 'ugeplan') }}

    response_variable: summary_response

  - variables:
      huskeliste_raw: >-
        {{ summary_response.response.speech.plain.speech
           | string
           | regex_replace(find='^\\s*```json\\s*', replace='')
           | regex_replace(find='\\s*```\\s*$', replace='')
           | trim }}
      huskeliste: >-
        {% set txt = huskeliste_raw %}
        {% if txt is string and txt|length > 0 and txt|regex_match('^\\s*\\[') %}
          {{ txt | from_json }}
        {% else %}
          {{ [] }}
        {% endif %}

  - choose:
      - conditions: "{{ (evt_name | string) | length > 0 }}"
        sequence:
          - event: "{{ evt_name }}"
            event_data:
              # Send den parse’de liste som 'huskeliste_json'
              huskeliste_json: "{{ huskeliste }}"
    default: []

  - action: input_text.set_value
    data:
      entity_id: !input output_helper
      value: >-
        {%- set lines = [] -%}
        {%- for item in huskeliste
              if (item.date | default('')) and (item.message | default('') | trim) -%}
          {%- set _ = lines.append('- **' ~ item.date ~ '**: ' ~ (item.message | trim)) -%}
        {%- endfor -%}
        {{ (lines | join('\n'))[:250] }}
